# -*- coding: utf-8 -*-
"""fatorial.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kd6EnlJtysn4BPRoMX-9CrdArgu_n-PQ
"""

def fat_recursiva(n):
  if n < 2:
    print('Eu uso recursividade')
    return 1
  else:
    return n*fat_recursiva(n-1)

def fat_sem_recursividade(n):
  print('Eu não uso recursividade')
  result = 1
  for i in range(2, n + 1):
    result *= i
  return result